# Chimera Intel - Application Configuration

# Global settings for network requests
network:
  timeout: 20.0 # Default timeout for all HTTP requests in seconds

# Configuration for specific modules
modules:
  footprint:
    # Define which DNS record types to query
    dns_records_to_query:
      - A
      - AAAA
      - MX
      - TXT
      - NS
      - CNAME
  
  web_analyzer:
    # Add settings for web analysis here in the future
    placeholder: true

  dark_web:
    # The SOCKS5 proxy address required to connect to the Tor network
    tor_proxy_url: "socks5://127.0.0.1:9150"

# Settings for report generation
reporting:
  graph:
  pdf:
    # Path to your company's logo. Leave blank to omit.
    # Example: "assets/logo.png"
    logo_path: ""
    # The main title for the report.
    title_text: "Chimera Intel - Intelligence Report"
    # Text to display in the footer of each page.
    footer_text: "Confidential | Prepared by Chimera Intel"
    # Pyvis graph physics settings
    # For more options: https://pyvis.readthedocs.io/en/latest/documentation.html#pyvis.network.Network.set_options
    physics_options: |
      var options = {
        "physics": {
          "barnesHut": {
            "gravitationalConstant": -40000,
            "centralGravity": 0.4,
            "springLength": 180
          },
          "minVelocity": 0.75
        }
      }