"""
RADINT (Radar Intelligence) Core Module

This module provides capabilities for analyzing Synthetic Aperture Radar (SAR) 
imagery to detect ground changes.

It performs algorithmic change detection using geospatial and CV libraries
to identify structural differences between two images within a defined
Area of Interest (AOI).

This file also contains the Typer CLI commands for the RADINT plugin.
"""

import logging
import asyncio
import typer
import rich
import rasterio
import rasterio.mask
import numpy as np
from shapely.geometry import Polygon
from skimage.metrics import structural_similarity
from skimage.transform import resize
from pathlib import Path
from datetime import datetime
from pydantic import BaseModel, Field
from typing import List, Optional
from chimera_intel.core.schemas import Coordinates

# Configure logger
logger = logging.getLogger(__name__)

# Define a threshold for change detection.
# SSIM returns a score between -1 and 1. 1 means identical.
SSIM_CHANGE_THRESHOLD = 0.95

# --- Pydantic Models ---

class SarChangeReport(BaseModel):
    """
    Represents a change detection report from SAR imagery analysis.
    This report is generated by algorithmic comparison.
    """
    area_of_interest: List[Coordinates] = Field(..., description="The bounding box or polygon of the analyzed area.")
    report_timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the analysis was performed.")
    change_detected: bool = Field(..., description="Whether significant change was detected.")
    change_summary: str = Field(..., description="A high-level summary of the detected changes.")
    detailed_description: str = Field(..., description="Detailed technical description of the analysis.")
    before_image_ref: str = Field(..., description="Identifier or path for the 'before' image.")
    after_image_ref: str = Field(..., description="Identifier or path for the 'after' image.")

# --- Core Client Class ---

class RadintClient:
    """
    Client for handling RADINT operations, focusing on SAR image analysis.
    This client performs its own algorithmic analysis and does not
    depend on an external AI client for its core logic.
    """
    def __init__(self):
        # This client is self-contained for its analysis logic.
        logger.info("RadintClient initialized.")

    def _clip_image_to_aoi(self, image_path: Path, aoi_poly: Polygon) -> Optional[np.ndarray]:
        """
        Loads a geospatial image and clips it to the given AOI polygon.
        """
        if not image_path.exists():
            raise FileNotFoundError(f"Image path not found: {image_path}")
            
        try:
            with rasterio.open(image_path) as src:
                # Ensure AOI is in the same CRS as the image
                # For this implementation, we assume WGS84 (EPSG:4326)
                if src.crs and not src.crs.is_geographic:
                    logger.warning(f"Image {image_path.name} CRS is {src.crs}, not geographic. Assuming AOI polygon matches CRS.")
                
                try:
                    out_image, out_transform = rasterio.mask.mask(src, [aoi_poly], crop=True)
                except ValueError as e:
                    # This often happens if the AOI polygon does not overlap the image
                    logger.warning(f"Could not mask image {image_path.name}: {e}. The AOI may not overlap the image.")
                    return None

                # We'll work with the first band for simplicity
                return out_image[0]
                
        except rasterio.errors.RasterioIOError as e:
            logger.error(f"Failed to read image {image_path}: {e}. Is it a valid GeoTIFF/image?")
            raise
        except Exception as e:
            logger.error(f"Error during image clipping: {e}")
            raise

    async def analyze_sar_imagery(
        self,
        before_image_path: Path,
        after_image_path: Path,
        aoi_coords: List[Coordinates]
    ) -> SarChangeReport:
        """
        Analyzes two Synthetic Aperture Radar (SAR) images ("before" and "after")
        to detect ground changes using internal, algorithmic analysis.
        """
        logger.info(f"Analyzing SAR imagery for change. Before: {before_image_path}, After: {after_image_path}")
        
        base_report_args = {
            "area_of_interest": aoi_coords,
            "before_image_ref": str(before_image_path),
            "after_image_ref": str(after_image_path)
        }

        try:
            # 1. Create Shapely Polygon from coordinates
            try:
                aoi_poly = Polygon([(c.lon, c.lat) for c in aoi_coords])
            except Exception as e:
                logger.error(f"Failed to create polygon from coordinates: {e}")
                return SarChangeReport(
                    **base_report_args,
                    change_detected=False,
                    change_summary="Analysis failed.",
                    detailed_description=f"Invalid AOI coordinates: {e}"
                )

            # 2. Load and clip "before" and "after" images to the AOI
            before_image_data = self._clip_image_to_aoi(before_image_path, aoi_poly)
            after_image_data = self._clip_image_to_aoi(after_image_path, aoi_poly)

            if before_image_data is None or after_image_data is None:
                return SarChangeReport(
                    **base_report_args,
                    change_detected=False,
                    change_summary="Analysis failed.",
                    detailed_description="Could not process images; AOI may not overlap with image bounds."
                )

            # 3. Ensure images are comparable
            if before_image_data.shape != after_image_data.shape:
                logger.warning(f"Image shapes differ: {before_image_data.shape} vs {after_image_data.shape}. Resizing 'after' image to match 'before'.")
                
                after_image_data = resize(after_image_data, before_image_data.shape,
                                          anti_aliasing=True, preserve_range=True)
                after_image_data = after_image_data.astype(before_image_data.dtype)

            if before_image_data.shape[0] < 7 or before_image_data.shape[1] < 7:
                # SSIM requires a window size (default is 7)
                return SarChangeReport(
                    **base_report_args,
                    change_detected=False,
                    change_summary="Analysis skipped.",
                    detailed_description=f"AOI is too small for analysis. Minimum size is 7x7 pixels. Got: {before_image_data.shape}"
                )

            # 4. Perform SSIM analysis
            data_range = np.max([before_image_data.max(), after_image_data.max()]) - np.min([before_image_data.min(), after_image_data.min()])
            if data_range == 0:
                data_range = 1.0 # Avoid division by zero if images are flat
            
            ssim_score = structural_similarity(
                before_image_data, 
                after_image_data, 
                data_range=data_range
            )
            
            # 5. Generate the report
            if ssim_score < SSIM_CHANGE_THRESHOLD:
                change_detected = True
                summary = "Significant structural change detected in AOI."
            else:
                change_detected = False
                summary = "No significant structural change detected in AOI."
            
            description = (
                f"Structural Similarity Index (SSIM) score: {ssim_score:.4f}. "
                f"Threshold for change: < {SSIM_CHANGE_THRESHOLD:.4f}. "
                f"Analyzed area shape: {before_image_data.shape} pixels."
            )

            return SarChangeReport(
                **base_report_args,
                change_detected=change_detected,
                change_summary=summary,
                detailed_description=description
            )

        except Exception as e:
            logger.error(f"Error during SAR image analysis: {e}")
            return SarChangeReport(
                **base_report_args,
                change_detected=False,
                change_summary="Analysis failed due to an internal error.",
                detailed_description=str(e)
            )

# --- Typer CLI Application ---

radint_app = typer.Typer(
    name="radint",
    help="Radar Intelligence (RADINT) tools for algorithmic SAR analysis."
)

def get_radint_client():
    """
    Utility function to instantiate the client.
    """
    return RadintClient()

@radint_app.command(name="analyze-sar", help="Analyze 'before' and 'after' SAR images for ground changes.")
def analyze_sar(
    before_image: Path = typer.Option(
        ..., 
        "--before", 
        help="File path to the 'before' geospatial image (e.g., .tif, .png).", 
        exists=True, 
        readable=True,
        resolve_path=True
    ),
    after_image: Path = typer.Option(
        ..., 
        "--after", 
        help="File path to the 'after' geospatial image (e.g., .tif, .png).", 
        exists=True, 
        readable=True,
        resolve_path=True
    ),
    aoi_coords: str = typer.Option(
        ..., 
        "--aoi", 
        help="Area of Interest, as comma-sep lon/lat pairs (e.g., '-118.3,34.0,-118.2,34.1,-118.1,34.0')."
    )
):
    """
    CLI command to perform algorithmic SAR imagery analysis.
    
    The AOI coordinates must be in Lon/Lat order (WGS84)
    and form a valid polygon (at least 3 points).
    """
    # Parse coordinates
    try:
        coords = []
        parts = aoi_coords.split(',')
        if len(parts) < 6 or len(parts) % 2 != 0: # Must have at least 3 pairs
            raise ValueError("AOI must be at least 3 comma-separated lon/lat pairs.")
        for i in range(0, len(parts), 2):
            # Note: User provides (Lon, Lat) for Shapely/Rasterio
            coords.append(Coordinates(lat=float(parts[i+1]), lon=float(parts[i])))
    except Exception as e:
        rich.print(f"[bold red]Error parsing coordinates: {e}[/bold red]")
        rich.print("Example format: 'lon1,lat1,lon2,lat2,lon3,lat3'")
        raise typer.Exit(code=1)

    rich.print(f"[bold cyan]Analyzing SAR change detection for {len(coords)} coordinates...[/bold cyan]")
    rich.print(f"  [b]Before:[/b] {before_image.name}")
    rich.print(f"  [b]After:[/b] {after_image.name}")

    client = get_radint_client()

    async def run_analysis():
        return await client.analyze_sar_imagery(
            before_image_path=before_image,
            after_image_path=after_image,
            aoi_coords=coords
        )

    # Run the analysis
    report: SarChangeReport = asyncio.run(run_analysis())
    
    # Print the report
    console = rich.get_console()
    console.print("\n[bold]--- SAR Analysis Report ---[/bold]")
    if report.change_detected:
        console.print(f"[bold green]Change Detected: YES[/bold green]")
    else:
        console.print(f"[bold yellow]Change Detected: NO[/bold yellow]")
    
    console.print(f"[b]Summary:[/b] {report.change_summary}")
    console.print(f"[b]Details:[/b] {report.detailed_description}")
    console.print(f"[b]Timestamp:[/b] {report.report_timestamp.isoformat()}")
    if "failed" in report.change_summary.lower() or "error" in report.detailed_description.lower():
        console.print(f"[bold red]Note: Analysis may have failed. See details.[/bold red]")