import typer
import os
import json
import google.generativeai as genai
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown

# --- CORRECTED Absolute Imports ---
# This import uses the full package path to find the database module.
from chimera_intel.core.database import get_aggregated_data_for_target

# Initialize a console for printing rich text
console = Console()

def generate_strategic_profile(aggregated_data: dict, api_key: str) -> str:
    """
    Uses a Generative AI model (Google Gemini Pro) to create a high-level strategic profile of a company.

    Args:
        aggregated_data (dict): The combined OSINT data for the target, fetched from the database.
        api_key (str): The Google AI API key for authentication.

    Returns:
        str: A markdown-formatted strategic analysis generated by the AI model.
    """
    if not api_key:
        return "Error: GOOGLE_API_KEY not found in .env file."
        
    # Configure the generative AI model with the provided API key
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel('gemini-pro')
    
    # Convert the aggregated data dictionary to a formatted JSON string for the prompt
    data_str = json.dumps(aggregated_data, indent=2, default=str)
    
    # This is the "prompt engineering" part. We give the AI a role (expert analyst),
    # context (the OSINT data), and a strict set of instructions for the output format.
    prompt = f"""
    As an expert business intelligence analyst, your task is to synthesize the following OSINT data into a high-level strategic profile of the target company.
    Focus on deducing their likely strategies based ONLY on the provided data.

    OSINT DATA:
    ```json
    {data_str}
    ```

    Based on the data, provide a concise analysis covering the following points. Present the entire output in Markdown format.
    
    1.  **Marketing & Sales Strategy:** Based on their web technologies, traffic sources, and news, what is their likely go-to-market strategy? Are they targeting consumers (B2C) or businesses (B2B)?
    2.  **Technology & Innovation Strategy:** Based on their tech stack and patents, are they a technology leader, a fast follower, or lagging in their industry? What are their R&D priorities?
    3.  **Expansion & Growth Strategy:** Are there any signals (e.g., in news, financials) that suggest they are planning to expand into new markets, launch new products, or are in a phase of aggressive growth?
    4.  **Overall Summary:** Provide a concluding paragraph summarizing their likely strategic position in the market.
    """
    
    try:
        # Send the prompt to the AI model and get the response
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"An error occurred with the Google AI API: {e}"


# --- Typer CLI Application ---

strategy_app = typer.Typer()

@strategy_app.command("run")
def run_strategy_analysis(
    target: str = typer.Argument(..., help="The target company to analyze (must have historical data).")
):
    """
    Generates an AI-powered strategic profile of a competitor by aggregating all known data.
    """
    console.print(Panel(f"[bold cyan]Generating Strategic Profile For:[/] {target}", title="Chimera Intel | Strategy Mapper", border_style="cyan"))

    # Step 1: Aggregate all available data from the database using our database function
    console.print(f" [dim]>[/dim] [dim]Aggregating historical data for '{target}'...[/dim]")
    aggregated_data = get_aggregated_data_for_target(target)
    
    if not aggregated_data:
        # If no data is found in the database, exit gracefully.
        raise typer.Exit()
        
    # Step 2: Send the aggregated data to the AI for analysis
    console.print(f" [dim]>[/dim] [dim]Submitting data to AI strategist for analysis...[/dim]")
    api_key = os.getenv("GOOGLE_API_KEY")
    strategic_profile = generate_strategic_profile(aggregated_data, api_key)
    
    # Step 3: Display the AI-generated markdown as rich text in the console
    console.print("\n--- [bold]Automated Strategic Profile[/bold] ---\n")
    console.print(Markdown(strategic_profile))