# The name of your GitHub Actions workflow
name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers on git push or pull request events for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Defines the jobs that will be executed
jobs:
  # --- NEW JOB FOR LINTING AND CODE QUALITY ---
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install quality tools directly
          pip install ruff black mypy

      - name: Run Ruff linter
        run: |
          ruff check .

      - name: Run Black formatter check
        run: |
          black --check .

      - name: Run MyPy type checker
        run: |
          mypy src/

  # --- EXISTING JOB FOR RUNNING TESTS ---
  test:
    # This job will run in parallel with the 'lint' job
    runs-on: ubuntu-latest
    # It needs the 'lint' job to succeed first
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the project with all its main and test dependencies in one go
          pip install -e ".[test]"

      - name: Run tests with pytest
        run: |
          pytest --cov=src/chimera_intel --cov-report=term-missing --cov-fail-under=85