# The name of your GitHub Actions workflow
name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers on git push or pull request events for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Defines the jobs that will be executed
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Defines the steps that will be executed in the job
    steps:
    # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Sets up Python version 3.11
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        # Cache dependencies to speed up future runs
        cache: 'pip'

    # Step 3: Install dependencies (THIS IS THE KEY PART)
    - name: Install dependencies
      run: |
        # Upgrade pip to the latest version
        python -m pip install --upgrade pip
        
        # --- THE CORRECT ORDER ---
        # 1. First, install your project and its specific dependencies from pyproject.toml
        # This will install the correct version of 'click' required by 'typer==0.12.3'
        pip install -e .
        
        # 2. Then, install the testing and quality tools
        pip install pytest pytest-cov ruff black mypy

    # Step 4: Run tests with pytest and check for code coverage
    - name: Run tests with pytest
      run: |
        pytest --cov=src/chimera_intel --cov-report=term-missing --cov-fail-under=85