# .github/workflows/quality_assurance.yml

name: Python Quality Assurance

on:
  push:
    branches: [ "main", "master", "20251002_IndustryIntel" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install all test dependencies in stages
        pip install -e ".[test]"
        pip install -e ".[test-heavy]"
        pip install black==24.8.0

    - name: Lint with Ruff
      run: ruff check .

    - name: Format code with Black
      run: black .

    - name: Type check with Mypy
      run: mypy src/

    - name: Run tests and check coverage
      run: pytest --cov=src/chimera_intel --cov-report=term-missing --cov-fail-under=85

    - name: Commit and push changes if formatting applied
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --cached --quiet && echo "✅ No changes to commit." || git commit -m "Apply Black formatting [ci skip]"
        git push origin HEAD:${{ github.ref_name }}