# The name of your workflow, which will appear in the "Actions" tab on GitHub
name: Python Quality Assurance

# --- When the workflow should run ---
on:
  # Run on every push to the 'main' or 'master' branch
  push:
    branches: [ "main", "master" ]
  # Also run on every pull request that targets 'main' or 'master'
  pull_request:
    branches: [ "main", "master" ]

# --- What the workflow does ---
jobs:
  # A single job in this workflow, we'll call it 'build'
  build:
    # Use the latest version of Ubuntu Linux to run the job
    runs-on: ubuntu-latest

    # --- Steps for the job ---
    # A sequence of tasks to be executed
    steps:
    # 1. Check out your code
    - name: Check out repository code
      uses: actions/checkout@v4

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        # Cache dependencies to speed up future runs
        cache: 'pip'

    # 3. Install all dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # This single command installs your project, its main dependencies,
        # and all testing/linting tools (including pytest-cov, ruff, black, mypy)
        # from your pyproject.toml file in one go.
        pip install -e ".[test]"

    # 4. Lint with Ruff
    - name: Lint with Ruff
      run: ruff check .

    # 5. Check formatting with Black
    - name: Check formatting with Black
      run: black --check .

    # 6. Type check with Mypy
    - name: Type check with Mypy
      run: mypy src/

    # 7. Run tests with Pytest and check coverage
    - name: Run tests and check coverage
      run: pytest --cov=src/chimera_intel --cov-report=term-missing --cov-fail-under=85